# based on https://github.com/eWaterCycle/ewatercycle-hype/blob/main/.github/workflows/test.yml
name: Python package

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false
    name: Run tests in mamba environment ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Download mamba environment.yml
        run:
          wget https://raw.githubusercontent.com/eWaterCycle/ewatercycle/main/environment.yml
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          init-shell: bash
      - name: Install dependencies
        shell: micromamba-shell {0}
        run: |
          pip3 install pytest
          pip3 install -e .
      - name: Test with pytest
        run: pytest
        shell: micromamba-shell {0}
